# Generated by Django 6.0.2 on 2026-02-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
