# Generated by Django 6.0.3 on 2026-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_group_add_user_remove_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_management',
            field=models.BooleanField(default=False),
        ),
    ]
